default_install_hook_types: [pre-push]
default_stages: [pre-push]

repos:
  - repo: local
    hooks:
      - id: make-format
        name: Make Format
        pass_filenames: false
        entry: make format
        language: system

      - id: make-lint
        name: Make Lint
        pass_filenames: false
        entry: make lint
        language: system
