[project]
name = "aidial-sdk"
version = "0.35.0rc"
description = "Framework to create applications and model adapters for AI DIAL"
authors = [{ name = "EPAM RAIL", email = "SpecialEPM-DIALDevTeam@epam.com" }]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "fastapi (>=0.51,<1.0)",
    "uvicorn (>=0.19,<1.0)",
    "pydantic (>=1.10.17,<3)",
    "wrapt (>=1.10,<2)",
]

[project.urls]
Homepage = "https://epam-rail.com"
Documentation = "https://epam-rail.com/dial_api"
Repository = "https://github.com/epam/ai-dial-sdk"

[project.optional-dependencies]
telemetry = [
    "opentelemetry-sdk (>=1.22.0,<2.0)",
    "opentelemetry-api (>=1.22.0,<2.0)",
    "opentelemetry-exporter-otlp-proto-grpc (>=1.22.0,<2.0)",
    "opentelemetry-instrumentation-aiohttp-client (>=0.43b0)",
    "opentelemetry-instrumentation-fastapi (>=0.43b0)",
    "opentelemetry-instrumentation-httpx (>=0.43b0)",
    "opentelemetry-instrumentation-logging (>=0.43b0)",
    "opentelemetry-instrumentation-requests (>=0.43b0)",
    "opentelemetry-instrumentation-system-metrics (>=0.43b0)",
    "opentelemetry-instrumentation-urllib (>=0.43b0)",
    "opentelemetry-exporter-prometheus (>=0.43b0)",
    "prometheus-client (>=0.17.1,<1.0)",
]
httpx = ["httpx (>=0.25.0,<1.0)"]

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"
pytest-asyncio = "^1.3.0"
nox = "^2023.4.22"
pillow = "^12.2.0"
httpx = "^0.25.0"
respx = "^0.21.1"
aiohttp = "^3.13.4"
aioresponses = "^0.7.6"
requests = "^2.33"
responses = "^0.25.3"

[tool.poetry.group.lint.dependencies]
pyright = "1.1.385"
ruff = "0.12.11"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
addopts = "--asyncio-mode=auto"
testpaths = ["tests"]
filterwarnings = [
    "error",
    # muting deprecation warnings coming from old pydantic
    "ignore::DeprecationWarning:pydantic.typing",
]
markers = ["slow: marker for slow running tests"]

[tool.pyright]
typeCheckingMode = "basic"
reportDeprecated = "error"
reportUnusedVariable = "error"
reportIncompatibleMethodOverride = "error"
exclude = [
    "examples/langchain_rag",
    "**/node_modules",
    "**/__pycache__",
    "**/.*",
    ".venv",
]

[tool.ruff]
line-length = 80
target-version = "py310"

[tool.ruff.lint]
select = [
    "ERA",  # flake8-eradicate
    "B",    # flake8-builtins
    "C4",   # flake8-comprehensions
    "SIM",  # flake8-simplify
    "B9",   # flake8-bugbear
    "E",    # pycodestyle
    "W",    # pycodestyle
    "F",    # pyflakes
    "I",    # flake8-isort
    "S",    # flake8-bandit
    "FURB", # refurb
    "UP",   # pyupgrade
]

ignore = [
    "E501", # string literal is too long
    "S101", # Use of `assert` detected
    "B904", # Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None`
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "B011", # Do not `assert False`
    "B006", # Do not use mutable data structures for argument defaults
    # "E731", # Do not assign a `lambda` expression, use a `def`
]
