DIAL_CONVERSATION_ID = "X-CONVERSATION-ID"
DIAL_JOB_TITLE = "X-JOB-TITLE"

DIAL_APPLICATION_PROPERTIES = "X-DIAL-APPLICATION-PROPERTIES"
DIAL_APPLICATION_ID = "X-DIAL-APPLICATION-ID"

DIAL_CACHE_BREAKPOINT_PATH = "X-DIAL-CACHE-BREAKPOINT-PATH"
DIAL_CACHE_EXPIRE_AT = "X-DIAL-CACHE-EXPIRE-AT"
DIAL_CACHE_EXTRA_METADATA = "X-DIAL-CACHE-EXTRA-METADATA"
DIAL_CACHE_POLICY = "X-DIAL-CACHE-POLICY"

DIAL_UPSTREAM_ENDPOINT = "X-UPSTREAM-ENDPOINT"
DIAL_UPSTREAM_KEY = "X-UPSTREAM-KEY"
DIAL_UPSTREAM_EXTRA_DATA = "X-UPSTREAM-EXTRA-DATA"
