name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_package_release.yml@4.4.1
    with:
      promote: true # HACK: skip RC phase, project does not require stabilization period before releasing stable versions
      python-version: "3.10"
      poetry-version: "2.2.1"
      code-checks-python-versions: '["3.10", "3.11", "3.12", "3.13"]'
    secrets: inherit
