name: Release Workflow

on:
  push:
    branches: [development, release-*]
  workflow_dispatch:
    inputs:
      promote:
        type: boolean
        default: false
        description: Promote release to stable (for release-* branches only)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_package_release.yml@4.0.0
    with:
      promote: ${{ github.event_name == 'workflow_dispatch' && inputs.promote }}
      python-version: "3.10"
      poetry-version: "2.2.1"
      code-checks-python-versions: '["3.10", "3.11", "3.12", "3.13"]'
    secrets: inherit
